<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#📊数据处理" data-toc-modified-id="📊数据处理-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>📊数据处理</a></span><ul class="toc-item"><li><span><a href="#MinMaxScaler(-feature_range-=-(-min_num,-max_num-)-)" data-toc-modified-id="MinMaxScaler(-feature_range-=-(-min_num,-max_num-)-)-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>MinMaxScaler( feature_range = ( min_num, max_num ) )</a></span><ul class="toc-item"><li><span><a href="#特征参数" data-toc-modified-id="特征参数-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>特征参数</a></span></li></ul></li><li><span><a href="#train_test_split(-X-,-Y-,-train_size-=-,-test_size-=-)" data-toc-modified-id="train_test_split(-X-,-Y-,-train_size-=-,-test_size-=-)-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>train_test_split( X , Y , train_size = , test_size = )</a></span><ul class="toc-item"><li><span><a href="#特征参数" data-toc-modified-id="特征参数-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>特征参数</a></span></li></ul></li><li><span><a href="#mean_absolute_error" data-toc-modified-id="mean_absolute_error-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>mean_absolute_error</a></span></li></ul></li><li><span><a href="#📊StandardScaler(-*-,-copy=-,-with_mean=-,-with_std=-)" data-toc-modified-id="📊StandardScaler(-*-,-copy=-,-with_mean=-,-with_std=-)-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>📊StandardScaler( * , copy= , with_mean= , with_std= )</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#特征参数" data-toc-modified-id="特征参数-2.0.1"><span class="toc-item-num">2.0.1&nbsp;&nbsp;</span>特征参数</a></span></li></ul></li></ul></li></ul></div>

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

---

# 📊数据处理

## MinMaxScaler( feature_range = ( min_num, max_num ) )  
---

   当数据(x)按照最小值中心化后，再按极差（最大值 - 最小值）缩放，数据移动了最小值个单位，并且会被收敛到[0,1]之间，而这个过程，就叫做数

据归一化(Normalization），又称Min-Max Scaling。

通过将每个特征缩放到给定范围来转换特征,归一化后的数据服从正态分布。

In [2]:
from sklearn.preprocessing import MinMaxScaler

# sklearn.preprocessing.MinMaxScaler( feature_range=(0, 1), *, copy=True, clip=False)

### 特征参数

**feature_range**：**元组** (最小值，最大值)，默认=(0, 1)
所需的转换数据范围。


**copy**：布尔，默认=真
设置为 False 以执行就地行规范化并避免复制(如果输入已经是一个 numpy 数组)。


**clip**：布尔，默认=假
设置为 True 以将 held-out 数据的转换值裁剪为提供的 feature range 。

In [5]:
# 示例数据
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
pd.DataFrame(data)

0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

In [6]:
# 使用实例1 ( fit ,transfrom分开执行 )
scaler = MinMaxScaler()            #实例化(对列)
scaler = scaler.fit(data)          #fit，在这里本质是生成min(x)和max(x)
result = scaler.transform(data)    #通过接口导出结果

In [9]:
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [10]:
# 使用实例2 ( fit_transfrom() )
result_ = scaler.fit_transform(data) #训练和导出结果一步达成
scaler.inverse_transform(result) #将归一化后的结果逆转

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [7]:
#使用MinMaxScaler的参数feature_range实现将数据归一化到[0,1]以外#的范围中

data1 = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
scaler = MinMaxScaler(feature_range=(5,10)) # 实例化 feature_range 数据压缩到的范围，默认为[0,1]
result = scaler.fit_transform(data1) #fit_transform一步导出结果
result

array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

---

## train_test_split( X , Y , train_size = , test_size = ) 
---
分割数据集函数,将数据分为训练集和测试集

In [ ]:
from sklearn.model_selection import train_test_split

# X_train, X_valid, y_train, y_valid = train_test_split(X, y, train_size=0.8, test_size=0.2,random_state=0) #随机状态

### 特征参数
**train_size**: 代表从数据集中分割的训练集

**test_size**: 代表从数据集中分割的测试集

---

## mean_absolute_error 
---
求MAE(平均绝对误差)

In [8]:
from sklearn.metrics import mean_absolute_error

# mean_absolute_error(y_val, y_predict)

# 📊StandardScaler( * , copy= , with_mean= , with_std= )
---
通过去除均值和缩放到单位方差来标准化特征。

样本x的标准分数计算如下：

z = (x - u) /s

其中 u 是训练样本的平均值，如果 with_mean=False 则为零，而 s 是训练样本的标准差，如果 with_std=False 则为 1。

In [9]:
from sklearn.preprocessing import StandardScaler

#class sklearn.preprocessing.StandardScaler(*, copy=True, with_mean=True, with_std=True)

### 特征参数
**copy**：布尔，默认=True.
如果为 False，请尽量避免复制并改为进行就地缩放。这不能保证总是在原地工作；例如如果数据不是NumPy 数组或scipy.sparse CSR 矩阵，则仍可能返回副本。

**with_mean**：布尔，默认=真
如果为 True，则在缩放之前将数据居中。当尝试在稀疏矩阵上时，这不起作用(并且会引发异常)，因为将它们居中需要构建一个密集矩阵，在常见的用例中，它可能太大而无法放入内存。

**with_std**：布尔，默认=真
如果为 True，则将数据缩放到单位方差(或等效地，单位标准差)。

In [11]:
scaler = StandardScaler() # 实例化 (按列)

scaler.fit(data)          # fit，本质是生成均值和方差
print(scaler.mean_)              # 查看均值的属性 mean_
print(scaler.var_)               # 查看方差的属性 var_

[-0.125  9.   ]
[ 0.546875 35.      ]


In [15]:
x_std = scaler.transform(data)    # 通过接口导出结果
print(x_std.mean())               # 导出的结果是一个数组，用mean()查看均值
print(x_std.std())                # 用 std() 查看方差

0.0
1.0


In [13]:
scaler.fit_transform(data) #使用fit_transform(data)一步达成结果

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [16]:
scaler.inverse_transform(x_std) #使用inverse_transform逆转标准化

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

---